apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  MYSQL_USER: {{ .Values.mysql.secrets.user }}
  MYSQL_PASSWORD: {{ .Values.mysql.secrets.password }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.secrets.rootPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  REDIS_PASSWORD: {{ .Values.redis.secrets.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  MYSQL_USER: {{ .Values.api.secrets.mysqlUser }}
  MYSQL_PASSWORD: {{ .Values.api.secrets.mysqlPassword }}
  REDIS_PASSWORD: {{ .Values.api.secrets.redisPassword }}
  AUTH_KEY: {{ .Values.api.secrets.authKey }}
