apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  namespace: aris-url-gen
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: aris-url-gen
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi 