apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: aris-url-gen
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: aris-url-gen
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: aris-url-gen-api
  namespace: aris-url-gen
spec:
  selector:
    app: aris-url-gen-api
  ports:
    - port: 8170
      targetPort: 8170
  type: LoadBalancer 